#!/usr/bin/env python3
"""Write a Cargo patch config for a clean local Bifrost engine checkout."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import tomllib


def git(engine_root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-c", "core.fsmonitor=false", "-C", str(engine_root), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def cargo_manifests(engine_root: Path) -> list[Path]:
    root_manifest = engine_root / "Cargo.toml"
    try:
        root_data = tomllib.loads(root_manifest.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise ValueError(f"cannot read engine manifest {root_manifest}: {error}") from error

    manifest_paths = {root_manifest}
    workspace = root_data.get("workspace", {})
    members = workspace.get("members", [])
    if not isinstance(members, list) or not all(isinstance(member, str) for member in members):
        raise ValueError(f"{root_manifest} has an invalid [workspace].members list")

    for member in members:
        for match in engine_root.glob(member):
            candidate = match / "Cargo.toml" if match.is_dir() else match
            if candidate.name == "Cargo.toml" and candidate.is_file():
                manifest_paths.add(candidate)

    return sorted(path for path in manifest_paths if path.is_file())


def patch_packages(engine_root: Path) -> dict[str, Path]:
    packages: dict[str, Path] = {}
    for manifest in cargo_manifests(engine_root):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError) as error:
            raise ValueError(f"cannot read engine manifest {manifest}: {error}") from error
        package = data.get("package", {})
        name = package.get("name") if isinstance(package, dict) else None
        if isinstance(name, str) and name.startswith("brokk-bifrost"):
            package_root = manifest.parent.resolve()
            try:
                package_root.relative_to(engine_root)
            except ValueError:
                raise ValueError(f"engine package escapes checkout: {manifest}") from None
            if name in packages:
                raise ValueError(f"duplicate engine package name {name!r}")
            packages[name] = package_root

    if not packages:
        raise ValueError(f"no brokk-bifrost* packages found in {engine_root}")
    return dict(sorted(packages.items()))


def render_config(packages: dict[str, Path]) -> str:
    lines = [
        "# Generated by scripts/configure-local-engine.py; do not commit this local override.",
        "[patch.crates-io]",
    ]
    for name, package_root in packages.items():
        escaped_path = json.dumps(str(package_root), ensure_ascii=False)
        lines.append(f"{name} = {{ path = {escaped_path} }}")
    return "\n".join(lines) + "\n"


def write_config(output: Path, content: str, engine_root: Path) -> None:
    output = output.resolve()
    try:
        output.relative_to(engine_root)
    except ValueError:
        pass
    else:
        raise ValueError(f"refusing to write into the engine checkout: {output}")

    if output.exists() and output.is_dir():
        raise ValueError(f"output is a directory: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output.parent,
            prefix=f".{output.name}.",
            delete=False,
        ) as temporary_file:
            temporary_path = Path(temporary_file.name)
            temporary_file.write(content)
        os.replace(temporary_path, output)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("engine", type=Path, help="path to the Bifrost engine Git checkout")
    parser.add_argument(
        "--expected-revision",
        help="require HEAD to match this Git revision (branch, tag, or commit)",
    )
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        help="allow modified, staged, or untracked files in the engine checkout",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="write elsewhere instead of .cargo/local-engine.toml (relative paths use the current directory)",
    )
    args = parser.parse_args()

    try:
        supplied_path = args.engine.expanduser().resolve(strict=True)
        engine_root = Path(git(supplied_path, "rev-parse", "--show-toplevel")).resolve()
        if supplied_path != engine_root:
            raise ValueError(f"engine path must be its Git checkout root: {engine_root}")

        revision = git(engine_root, "rev-parse", "--verify", "HEAD^{commit}")
        if args.expected_revision:
            expected = git(
                engine_root,
                "rev-parse",
                "--verify",
                "--end-of-options",
                f"{args.expected_revision}^{{commit}}",
            )
            if revision != expected:
                raise ValueError(
                    f"engine revision mismatch: expected {expected}, found {revision}"
                )

        dirty = git(engine_root, "status", "--porcelain=v1", "--untracked-files=normal")
        if dirty and not args.allow_dirty:
            raise ValueError(
                "engine checkout is dirty; commit or discard its changes, or pass --allow-dirty"
            )
        if dirty:
            print("warning: allowing a dirty engine checkout", file=sys.stderr)

        output = args.output or (Path(__file__).resolve().parents[1] / ".cargo/local-engine.toml")
        packages = patch_packages(engine_root)
        write_config(output, render_config(packages), engine_root)
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        detail = error.stderr.strip() if isinstance(error, subprocess.CalledProcessError) else str(error)
        print(f"configure-local-engine: {detail}", file=sys.stderr)
        return 1

    print(f"Wrote {output.resolve()} for {len(packages)} packages at {revision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
